baseURL = "https://tobias-njcit.github.io/"
languageCode = "ja-JP"
title = "日本語二列"
theme = "PaperMod"
[pagination]
  pagerSize = 5

[params]
  defaultTheme = "dark"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  description = "随筆"

  [params.homeInfoParams]
    Title = "日本語二列"
    Content = "暴言、妄想、執着心"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tobias-njcit"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/nihonniretsu"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
